FROM nginx@sha256:4a73073bd557c65b759505da037898b61f1be6cbcc3c2c3aeac22d2a470c1752

COPY nginx.conf /etc/nginx/nginx-http.conf
COPY nginx-https.conf.template /etc/nginx/nginx-https.conf.template
COPY entrypoint.sh /docker-entrypoint.sh

RUN chmod 0555 /docker-entrypoint.sh \
    && rm -f /etc/nginx/conf.d/default.conf

ENTRYPOINT ["/bin/sh", "/docker-entrypoint.sh"]
